import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { Toaster } from "react-hot-toast";

const PlusJakatraSans = Plus_Jakarta_Sans({
  variable: "--plus_jakatra_sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={` ${PlusJakatraSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col justify-between gap-20">
        <Navbar></Navbar>
        <div className="container mx-auto grow pt-40">{children}</div>
        <Footer></Footer>
        <Toaster></Toaster>
      </body>
    </html>
  );
}
